import Link from "next/link";
import { notFound } from "next/navigation";
import { Archive, Pencil, Plus } from "lucide-react";
import { archiveLifeAreaAction } from "@/app/planning-actions";
import { AppShell } from "@/components/app-shell";
import { TaskRow } from "@/components/task-row";
import { getCurrentUserId } from "@/server/auth/current-user";
import { getLifeAreaDetail } from "@/server/repositories/planning";
export const dynamic = "force-dynamic";
export default async function LifeAreaPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const detail = await getLifeAreaDetail(await getCurrentUserId(), id); if (!detail) notFound(); return <AppShell><header className="border-b border-border pb-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/life" className="text-xs text-muted-foreground">Life areas /</Link><h1 className="mt-3 text-4xl font-medium tracking-tight">{detail.area.name}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{detail.area.description || "No description yet."}</p></div><div className="flex gap-2"><Link href={`/life/${id}/edit`} className="button-secondary"><Pencil size={14} />Edit</Link>{detail.area.status === "active" ? <form action={archiveLifeAreaAction}><input type="hidden" name="id" value={id} /><button className="button-secondary"><Archive size={14} />Archive</button></form> : null}</div></div><div className="mt-6 flex gap-8"><Metric label="Importance" value={detail.area.importance} /><Metric label="Satisfaction" value={detail.area.satisfaction} /><Metric label="Open tasks" value={detail.tasks.length} /></div></header><div className="grid gap-10 pt-9 lg:grid-cols-2"><Collection title="Goals" action={`/goals/new?lifeArea=${id}`} items={detail.goals.map((item) => ({ href: `/goals/${item.id}`, title: item.title, meta: `${item.progress}% · ${item.status}` }))} /><Collection title="Projects" action={`/projects/new?lifeArea=${id}`} items={detail.projects.map((item) => ({ href: `/projects/${item.id}`, title: item.title, meta: `${item.progress}% · ${item.status}` }))} /></div><section className="mt-10"><div className="flex items-center justify-between"><h2 className="section-title">Open tasks</h2><Link href={`/tasks/new?lifeArea=${id}`} className="button-secondary"><Plus size={14} />Add task</Link></div><div className="mt-4 border-t border-border">{detail.tasks.length ? detail.tasks.map((task) => <TaskRow key={task.id} task={task} />) : <p className="py-8 text-center text-sm text-muted-foreground">No open tasks.</p>}</div></section></AppShell>; }
function Metric({ label, value }: { label: string; value: number | null }) { return <div><p className="font-mono text-xl">{value ?? "—"}</p><p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p></div>; }
function Collection({ title, action, items }: { title: string; action: string; items: { href: string; title: string; meta: string }[] }) { return <section><div className="flex items-center justify-between"><h2 className="section-title">{title}</h2><Link href={action} className="button-icon-quiet" aria-label={`Add ${title}`}><Plus size={15} /></Link></div><div className="mt-4 divide-y divide-border border-y border-border">{items.length ? items.map((item) => <Link key={item.href} href={item.href} className="block py-4"><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.meta}</p></Link>) : <p className="py-8 text-center text-sm text-muted-foreground">None yet.</p>}</div></section>; }
