import type { Metadata } from "next";
import Link from "next/link";
import { CalendarDays, ChevronLeft, ChevronRight, ListTodo, Plus, Square } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { addDays, dateKeys, itemDateKey, periodFor, plannedMinutes, type CalendarItem, type CalendarView } from "@/lib/domain/calendar";
import { dateKeyInTimeZone } from "@/lib/domain/today";
import { getCurrentUser } from "@/server/auth/current-user";
import { listCalendarItems } from "@/server/repositories/calendar";

export const metadata: Metadata = { title: "Calendar" }; export const dynamic = "force-dynamic";
const views: CalendarView[] = ["day", "week", "month"];
export default async function CalendarPage({ searchParams }: { searchParams: Promise<{ view?: string; date?: string }> }) {
  const query = await searchParams; const user = await getCurrentUser(); const today = dateKeyInTimeZone(new Date(), user.timezone); const view = views.includes(query.view as CalendarView) ? query.view as CalendarView : "week"; const date = /^\d{4}-\d{2}-\d{2}$/.test(query.date ?? "") ? query.date! : today; const period = periodFor(date, view, user.timezone); const data = await listCalendarItems(user.id, period.start, period.end);
  const items: CalendarItem[] = [
    ...data.events.map((event) => ({ id: event.id, kind: "event" as const, title: event.title, startAt: event.startAt, endAt: event.endAt, allDay: Boolean(event.allDay), status: event.status })),
    ...data.tasks.filter((task) => task.scheduledStart && task.scheduledEnd).map((task) => ({ id: task.id, kind: "task" as const, title: task.title, startAt: task.scheduledStart!, endAt: task.scheduledEnd! })),
    ...data.blocks.map(({ block }) => ({ id: block.id, kind: "block" as const, title: block.title, startAt: block.startAt, endAt: block.endAt, taskId: block.taskId, status: block.status }))
  ].sort((a, b) => a.startAt.getTime() - b.startAt.getTime());
  const direction = view === "day" ? 1 : view === "week" ? 7 : 31; const previous = view === "month" ? monthShift(date, -1) : addDays(date, -direction); const next = view === "month" ? monthShift(date, 1) : addDays(date, direction); const label = rangeLabel(period.start, new Date(period.end.getTime() - 1), view, user.timezone);
  return <AppShell><header className="border-b pb-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="section-kicker">Plan time</p><h1 className="mt-2 text-4xl font-medium tracking-tight">Calendar</h1><p className="mt-2 text-sm text-muted-foreground">{label} · {formatMinutes(plannedMinutes(items))} planned</p></div><div className="flex flex-wrap gap-2"><Link href={`/calendar/events/new?date=${date}`} className="button-secondary"><CalendarDays size={15} />Event</Link><Link href={`/calendar/blocks/new?date=${date}`} className="button-secondary"><Square size={15} />Time block</Link><Link href={`/calendar/schedule?date=${date}`} className="button-primary"><Plus size={15} />Schedule task</Link></div></div><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><nav aria-label="Calendar period" className="flex items-center gap-1"><Link href={`?view=${view}&date=${previous}`} className="button-icon-quiet" aria-label="Previous period"><ChevronLeft size={18} /></Link><Link href={`?view=${view}&date=${today}`} className="button-secondary">Today</Link><Link href={`?view=${view}&date=${next}`} className="button-icon-quiet" aria-label="Next period"><ChevronRight size={18} /></Link><span className="ml-2 text-sm font-medium">{label}</span></nav><nav aria-label="Calendar view" className="grid grid-cols-3 rounded-xl border bg-card p-1">{views.map((item) => <Link key={item} href={`?view=${item}&date=${date}`} aria-current={item === view ? "page" : undefined} className={`rounded-lg px-4 py-2 text-center text-xs capitalize ${item === view ? "bg-foreground text-background" : "text-muted-foreground"}`}>{item}</Link>)}</nav></div></header>
    <div className="pt-7">{view === "month" ? <MonthView date={date} items={items} timeZone={user.timezone} /> : <Agenda dates={dateKeys(period.startDate, period.endDate)} items={items} timeZone={user.timezone} week={view === "week"} />}</div>
  </AppShell>;
}

function Agenda({ dates, items, timeZone, week }: { dates: string[]; items: CalendarItem[]; timeZone: string; week: boolean }) { return <div className={week ? "grid gap-4 md:grid-cols-2 xl:grid-cols-7" : "mx-auto max-w-3xl"}>{dates.map((date) => { const day = periodFor(date, "day", timeZone); const dayItems = items.filter((item) => item.startAt < day.end && item.endAt > day.start); return <section key={date} aria-labelledby={`day-${date}`} className="min-w-0 rounded-2xl border bg-card p-4"><Link href={`/calendar?view=day&date=${date}`} className="block"><p className="font-mono text-[10px] uppercase text-muted-foreground">{new Intl.DateTimeFormat("en-US", { timeZone: "UTC", weekday: "short" }).format(new Date(`${date}T12:00:00Z`))}</p><h2 id={`day-${date}`} className="mt-1 text-xl font-medium">{Number(date.slice(8))}</h2></Link><div className="mt-4 space-y-2">{dayItems.length ? dayItems.map((item) => <CalendarCard key={`${item.kind}-${item.id}`} item={item} timeZone={timeZone} />) : <p className="py-4 text-xs text-muted-foreground">Open time</p>}</div></section>; })}</div>; }
function CalendarCard({ item, timeZone }: { item: CalendarItem; timeZone: string }) { const Icon = item.kind === "event" ? CalendarDays : item.kind === "task" ? ListTodo : Square; const href = item.kind === "event" ? `/calendar/events/${item.id}/edit` : item.kind === "task" ? `/calendar/schedule/${item.id}` : `/calendar/blocks/${item.id}/edit`; return <Link href={href} aria-label={`${item.kind}: ${item.title}`} className={`block rounded-xl border-l-4 p-3 ${item.kind === "event" ? "border-l-foreground bg-secondary" : item.kind === "task" ? "border-l-success bg-card" : "border-l-amber-600 bg-amber-50/50"}`}><span className="flex items-center gap-1.5 font-mono text-[9px] uppercase tracking-wide text-muted-foreground"><Icon size={11} />{item.kind === "block" ? "Time block" : item.kind}</span><p className="mt-1.5 truncate text-xs font-medium">{item.title}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.allDay ? "All day" : timeLabel(item.startAt, item.endAt, timeZone)}</p></Link>; }
function MonthView({ date, items, timeZone }: { date: string; items: CalendarItem[]; timeZone: string }) { const first = `${date.slice(0, 7)}-01`; const monthEnd = monthShift(first, 1); const leading = (new Date(`${first}T12:00:00Z`).getUTCDay() + 6) % 7; const cells = [...Array(leading).fill(null), ...dateKeys(first, monthEnd)]; return <div><div className="mb-2 hidden grid-cols-7 text-center font-mono text-[10px] uppercase text-muted-foreground sm:grid">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((day) => <span key={day}>{day}</span>)}</div><div className="grid grid-cols-7 overflow-hidden rounded-2xl border bg-card">{cells.map((day, index) => day ? <Link key={day} href={`/calendar?view=day&date=${day}`} className="min-h-20 border-b border-r p-2 sm:min-h-28"><span className="text-xs font-medium">{Number(day.slice(8))}</span>{(() => { const dayItems = items.filter((item) => itemDateKey(item.startAt, timeZone) === day); const counts = { event: dayItems.filter((x) => x.kind === "event").length, task: dayItems.filter((x) => x.kind === "task").length, block: dayItems.filter((x) => x.kind === "block").length }; return <div className="mt-2 space-y-1 text-[9px] text-muted-foreground">{counts.event ? <p>E {counts.event}</p> : null}{counts.task ? <p>T {counts.task}</p> : null}{counts.block ? <p>B {counts.block}</p> : null}</div>; })()}</Link> : <div key={`blank-${index}`} className="min-h-20 border-b border-r bg-secondary/30 sm:min-h-28" />)}</div></div>; }
function timeLabel(start: Date, end: Date, timeZone: string) { const format = new Intl.DateTimeFormat("en-US", { timeZone, hour: "numeric", minute: "2-digit" }); return `${format.format(start)}–${format.format(end)}`; }
function rangeLabel(start: Date, end: Date, view: CalendarView, timeZone: string) { const format = new Intl.DateTimeFormat("en-US", { timeZone, month: "short", day: "numeric", year: view === "month" ? "numeric" : undefined }); return view === "day" ? format.format(start) : view === "month" ? new Intl.DateTimeFormat("en-US", { timeZone, month: "long", year: "numeric" }).format(start) : `${format.format(start)} – ${format.format(end)}`; }
function monthShift(date: string, amount: number) { const [year, month] = date.split("-").map(Number); return new Date(Date.UTC(year!, month! - 1 + amount, 1, 12)).toISOString().slice(0, 10); }
function formatMinutes(minutes: number) { return minutes >= 60 ? `${Math.floor(minutes / 60)}h ${minutes % 60}m` : `${minutes}m`; }
