import Link from "next/link";
import { Plus } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { getCurrentUserId } from "@/server/auth/current-user";
import { getGoalOptions, listProjects, type ProjectFilter } from "@/server/repositories/planning";
export const dynamic = "force-dynamic";
export default async function ProjectsPage({ searchParams }: { searchParams: Promise<{ status?: string; goal?: string; area?: string }> }) { const p = await searchParams; const filter = (["active", "planned", "paused", "completed", "archived", "all"].includes(p.status ?? "") ? p.status : "active") as ProjectFilter; const userId = await getCurrentUserId(); const [rows, options] = await Promise.all([listProjects(userId, filter, p.goal, p.area), getGoalOptions(userId)]); return <AppShell><header className="flex flex-col gap-5 border-b border-border pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="section-kicker">Focused outcomes</p><h1 className="mt-2 text-4xl font-medium tracking-tight">Projects</h1><p className="mt-2 text-sm text-muted-foreground">Finite bodies of work that move your goals forward.</p></div><Link href="/projects/new" className="button-primary self-start"><Plus size={16} />New project</Link></header><form className="mt-7 grid gap-3 sm:grid-cols-3"><Filter name="status" label="Status" value={filter} options={["active", "planned", "paused", "completed", "archived", "all"]} /><Owned name="goal" label="Goal" value={p.goal} options={options.goals.map((x) => ({ id: x.id, label: x.title }))} /><Owned name="area" label="Life area" value={p.area} options={options.lifeAreas.map((x) => ({ id: x.id, label: x.name }))} /><button className="sr-only">Apply filters</button></form><div className="mt-7 divide-y divide-border border-y border-border">{rows.length ? rows.map((project) => <Link key={project.id} href={`/projects/${project.id}`} className="grid gap-3 py-5 sm:grid-cols-[minmax(0,1fr)_120px_100px] sm:items-center"><div><h2 className="font-medium tracking-tight">{project.title}</h2><p className="mt-1 text-xs text-muted-foreground">{project.goalTitle || "Independent project"}{project.lifeAreaName ? ` · ${project.lifeAreaName}` : ""}{project.deadline ? ` · Due ${project.deadline}` : ""}</p></div><div><div className="h-1.5 rounded-full bg-secondary"><div className="h-full rounded-full bg-foreground" style={{ width: `${project.progress}%` }} /></div><p className="mt-1 font-mono text-[10px] text-muted-foreground">{Number(project.progress)}%</p></div><span className="text-xs capitalize text-muted-foreground sm:text-right">{project.status}</span></Link>) : <div className="py-16 text-center text-sm text-muted-foreground">No projects in this view.</div>}</div></AppShell>; }
function Filter({ name, label, value, options }: { name: string; label: string; value: string; options: string[] }) { return <label className="space-y-1 text-xs text-muted-foreground">{label}<select name={name} defaultValue={value} className="input capitalize">{options.map((x) => <option key={x} value={x}>{x}</option>)}</select></label>; }
function Owned({ name, label, value, options }: { name: string; label: string; value?: string; options: { id: string; label: string }[] }) { return <label className="space-y-1 text-xs text-muted-foreground">{label}<select name={name} defaultValue={value ?? ""} className="input"><option value="">All</option>{options.map((x) => <option key={x.id} value={x.id}>{x.label}</option>)}</select></label>; }
