"use client";

import { useActionState, useEffect, useState } from "react";
import { cancelFocusAction, endFocusAction, logHabitAction, manualFocusAction, saveHabitAction, startFocusAction, updateFocusAction } from "@/app/behavior-actions";
import { initialActionState } from "@/lib/action-state";
import { dateTimeLocalValue } from "@/lib/domain/date-time";
import { ActionFeedback } from "./action-feedback"; import { SubmitButton } from "./submit-button";

type Option = { id: string; label: string }; type Options = { tasks: Option[]; projects: Option[]; goals: Option[]; lifeAreas: Option[] };
type HabitEdit = { id: string; name: string; description: string | null; lifeAreaId: string | null; trackingType: string; unit: string | null; targetValue: string | null; frequencyType: string; targetFrequency: number | null; status: string; position: number };
export function HabitForm({ habit, lifeAreas }: { habit?: HabitEdit; lifeAreas: Option[] }) { const [state, action] = useActionState(saveHabitAction, initialActionState); const [type, setType] = useState(habit?.trackingType ?? "boolean"); return <form action={action} className="space-y-6">{habit ? <input type="hidden" name="id" value={habit.id} /> : null}<input type="hidden" name="status" value={habit?.status ?? "active"} /><input type="hidden" name="position" value={habit?.position ?? 0} /><Field label="Habit name" name="name" required defaultValue={habit?.name} /><TextArea label="Description" name="description" defaultValue={habit?.description ?? ""} /><div className="grid gap-5 sm:grid-cols-2"><TextSelect label="Tracking" name="trackingType" value={type} options={["boolean", "quantity", "duration", "frequency"]} onChange={setType} /><Select label="Life area" name="lifeAreaId" value={habit?.lifeAreaId} options={lifeAreas} /></div>{type === "quantity" ? <div className="grid gap-5 sm:grid-cols-2"><Field label="Daily target" name="targetValue" type="number" min="0.0001" step="any" required defaultValue={habit?.targetValue ?? ""} /><Field label="Unit" name="unit" required defaultValue={habit?.unit ?? ""} /></div> : null}{type === "duration" ? <Field label="Daily target (minutes)" name="targetValue" type="number" min="1" step="1" required defaultValue={habit?.targetValue ?? ""} /> : null}{type === "frequency" ? <div className="grid gap-5 sm:grid-cols-2"><TextSelect label="Period" name="frequencyType" value={habit?.frequencyType ?? "weekly"} options={["daily", "weekly"]} /><Field label="Target occurrences" name="targetFrequency" type="number" min="1" step="1" required defaultValue={habit?.targetFrequency ?? ""} /></div> : <input type="hidden" name="frequencyType" value="daily" />}<FormEnd state={state} label="Save habit" /></form>; }

export function HabitLogControl({ habitId, date, value, type, target, unit }: { habitId: string; date: string; value: number; type: string; target: number; unit?: string | null }) { const [state, action] = useActionState(logHabitAction, initialActionState); const boolean = type === "boolean"; return <form action={action} className="flex flex-wrap items-end gap-2"><input type="hidden" name="habitId" value={habitId} /><input type="hidden" name="logDate" value={date} />{boolean ? <input type="hidden" name="value" value={value >= 1 ? 0 : 1} /> : <div><label className="sr-only" htmlFor={`habit-${habitId}`}>Log {unit || "value"}</label><input id={`habit-${habitId}`} className="input w-24" name="value" type="number" min="0" step={type === "frequency" ? "1" : "any"} defaultValue={value} /></div>}<SubmitButton>{boolean ? value >= 1 ? "Mark not done" : "Done" : `Log / ${target} ${unit ?? ""}`}</SubmitButton><ActionFeedback state={state} /></form>; }

export function FocusStartForm({ options }: { options: Options }) { const [state, action] = useActionState(startFocusAction, initialActionState); return <form action={action} className="space-y-5"><ContextFields options={options} /><Field label="Planned minutes" name="plannedMinutes" type="number" min="1" step="1" placeholder="Optional" /><FormEnd state={state} label="Start focus" /></form>; }
export function ManualFocusForm({ options }: { options: Options }) { const [state, action] = useActionState(manualFocusAction, initialActionState); return <form action={action} className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><Field label="Started" name="startedAt" type="datetime-local" required defaultValue={dateTimeLocalValue(new Date())} /><Field label="Duration (minutes)" name="durationMinutes" type="number" min="1" step="1" required /></div><ContextFields options={options} /><TextArea label="Notes" name="notes" defaultValue="" /><FormEnd state={state} label="Record focus" /></form>; }
export function FocusEditForm({ session, options }: { session: { id: string; taskId: string | null; projectId: string | null; goalId: string | null; lifeAreaId: string | null; notes: string | null }; options: Options }) { const [state, action] = useActionState(updateFocusAction, initialActionState); return <form action={action} className="space-y-5"><input type="hidden" name="id" value={session.id} /><ContextFields options={options} values={session} /><TextArea label="Notes" name="notes" defaultValue={session.notes ?? ""} /><FormEnd state={state} label="Save session details" /></form>; }

export function ActiveFocusTimer({ session }: { session: { id: string; startedAt: Date; plannedMinutes: number | null; taskId?: string | null; projectId?: string | null; goalId?: string | null; lifeAreaId?: string | null } }) { const [now, setNow] = useState(() => Date.now()); useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []); const seconds = Math.max(0, Math.floor((now - new Date(session.startedAt).getTime()) / 1000)); const display = `${String(Math.floor(seconds / 3600)).padStart(2, "0")}:${String(Math.floor((seconds % 3600) / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; const context = session.taskId ? "Task-linked" : session.projectId ? "Project-linked" : session.goalId ? "Goal-linked" : session.lifeAreaId ? "Life-area focus" : "Unlinked focus"; return <section aria-live="polite" aria-label="Active focus session" className="rounded-3xl bg-ink p-7 text-center text-ink-foreground sm:p-10"><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-ink-muted">Focus in progress · {context}</p><p className="mt-5 font-mono text-5xl tracking-tight sm:text-7xl">{display}</p><p className="mt-3 text-xs text-ink-muted">Server start time is authoritative{session.plannedMinutes ? ` · ${session.plannedMinutes} min planned` : ""}</p><div className="mt-8 flex justify-center gap-3"><form action={endFocusAction}><input type="hidden" name="id" value={session.id} /><button className="button-primary bg-white text-black" aria-label="End active focus session">End session</button></form><form action={cancelFocusAction}><input type="hidden" name="id" value={session.id} /><button className="button-secondary border-white/30 bg-transparent text-white" aria-label="Cancel active focus session">Cancel</button></form></div></section>; }

function ContextFields({ options, values }: { options: Options; values?: { taskId: string | null; projectId: string | null; goalId: string | null; lifeAreaId: string | null } }) { return <div className="grid gap-5 sm:grid-cols-2"><Select label="Task" name="taskId" value={values?.taskId} options={options.tasks} /><Select label="Project" name="projectId" value={values?.projectId} options={options.projects} /><Select label="Goal" name="goalId" value={values?.goalId} options={options.goals} /><Select label="Life area" name="lifeAreaId" value={values?.lifeAreaId} options={options.lifeAreas} /></div>; }
function FormEnd({ state, label }: { state: typeof initialActionState; label: string }) { return <div className="flex flex-col-reverse gap-3 border-t pt-5 sm:flex-row sm:items-center sm:justify-between"><ActionFeedback state={state} /><SubmitButton>{label}</SubmitButton></div>; }
function Field({ label, name, ...props }: { label: string; name: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <div className="space-y-2"><label className="label" htmlFor={name}>{label}</label><input className="input" id={name} name={name} {...props} /></div>; }
function TextArea({ label, name, defaultValue }: { label: string; name: string; defaultValue: string }) { return <div className="space-y-2"><label className="label" htmlFor={name}>{label}</label><textarea className="input min-h-24 resize-y" id={name} name={name} defaultValue={defaultValue} /></div>; }
function Select({ label, name, options, value }: { label: string; name: string; options: Option[]; value?: string | null }) { return <div className="space-y-2"><label className="label" htmlFor={name}>{label}</label><select className="input" id={name} name={name} defaultValue={value ?? ""}><option value="">None</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></div>; }
function TextSelect({ label, name, options, value, onChange }: { label: string; name: string; options: string[]; value: string; onChange?: (value: string) => void }) { const control = onChange ? { value, onChange: (event: React.ChangeEvent<HTMLSelectElement>) => onChange(event.target.value) } : { defaultValue: value }; return <div className="space-y-2"><label className="label" htmlFor={name}>{label}</label><select className="input capitalize" id={name} name={name} {...control}>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></div>; }
