import Link from "next/link";
import { Plus } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { getCurrentUserId } from "@/server/auth/current-user";
import { getGoalOptions, listGoals, type GoalFilter } from "@/server/repositories/planning";
export const dynamic = "force-dynamic";
export default async function GoalsPage({ searchParams }: { searchParams: Promise<{ status?: string; level?: string; area?: string }> }) { const p = await searchParams; const filter = (["active", "completed", "paused", "archived", "all"].includes(p.status ?? "") ? p.status : "active") as GoalFilter; const userId = await getCurrentUserId(); const [rows, options] = await Promise.all([listGoals(userId, filter, p.area, p.level), getGoalOptions(userId)]); return <AppShell><Header /><form className="mt-7 grid gap-3 sm:grid-cols-3"><Filter name="status" label="Status" value={filter} options={["active", "completed", "paused", "archived", "all"]} /><Filter name="level" label="Level" value={p.level} options={["long_term", "yearly", "quarterly", "general"]} empty="All levels" /><label className="space-y-1 text-xs text-muted-foreground">Life area<select name="area" defaultValue={p.area ?? ""} className="input"><option value="">All areas</option>{options.lifeAreas.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button className="sr-only">Apply filters</button></form><div className="mt-7 divide-y divide-border border-y border-border">{rows.length ? rows.map((goal) => <Link key={goal.id} href={`/goals/${goal.id}`} className="grid gap-3 py-5 sm:grid-cols-[minmax(0,1fr)_120px_100px] sm:items-center"><div><div className="flex items-center gap-2"><h2 className="font-medium tracking-tight">{goal.title}</h2>{goal.parentGoalId ? <span className="text-[10px] text-muted-foreground">Nested</span> : null}</div><p className="mt-1 text-xs capitalize text-muted-foreground">{goal.level.replace("_", " ")}{goal.lifeAreaName ? ` · ${goal.lifeAreaName}` : ""}{goal.deadline ? ` · Due ${goal.deadline}` : ""}</p></div><Progress value={Number(goal.progress)} /><span className="text-xs capitalize text-muted-foreground sm:text-right">{goal.status}</span></Link>) : <Empty />}</div></AppShell>; }
function Header() { return <header className="flex flex-col gap-5 border-b border-border pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="section-kicker">Direction</p><h1 className="mt-2 text-4xl font-medium tracking-tight">Goals</h1><p className="mt-2 text-sm text-muted-foreground">Connect long-range intent to work you can execute.</p></div><Link href="/goals/new" className="button-primary self-start"><Plus size={16} />New goal</Link></header>; }
function Filter({ name, label, value, options, empty }: { name: string; label: string; value?: string; options: string[]; empty?: string }) { return <label className="space-y-1 text-xs text-muted-foreground">{label}<select name={name} defaultValue={value ?? ""} className="input capitalize">{empty ? <option value="">{empty}</option> : null}{options.map((x) => <option key={x} value={x}>{x.replace("_", " ")}</option>)}</select></label>; }
function Progress({ value }: { value: number }) { return <div><div className="h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full bg-foreground" style={{ width: `${value}%` }} /></div><p className="mt-1 font-mono text-[10px] text-muted-foreground">{value}%</p></div>; }
function Empty() { return <div className="py-16 text-center"><p className="text-sm font-medium">No goals in this view.</p><Link href="/goals/new" className="mt-3 inline-block text-xs underline">Create a goal</Link></div>; }
